### ISSUE TITLE
Compile error on Mac

### ISSUE THREAD

**Issue by maziac** [chernandezba/zesarux#2]
Hi,

I tried to compile for Mac but get this error:

scrcocoa.m:1282:27: error: use of undeclared identifier 'NSWindowStyleMaskBorderless'

I have xcode 8.2.1 installed and run
OSX 10.11.6

BR,

**Comment by maziac** [comment]
Hi,

the problem seems not to exist on Sierra.
I'm still on Capitan.

If anyone wants to compile on Capitan as well, here is what you need to do.
Simply add this to the scrcocoa.m file:

#ifndef MAC_OS_X_VERSION_10_5
#define MAC_OS_X_VERSION_10_5 1050
#endif


**enum {
	NSWindowStyleMaskBorderless  = 0,
	NSEventModifierFlagShift = 1 << 17,
	NSEventModifierFlagControl = 1 << 18,
	NSEventModifierFlagOption = 1 << 19,
	NSEventModifierFlagCommand = 1 << 20,
	NSWindowStyleMaskTitled = 1 << 0,
	NSWindowStyleMaskMiniaturizable = 1 << 2,
	NSWindowStyleMaskClosable = 1 << 1,
	NSWindowStyleMaskResizable = 1 << 3
	};**

Aferwards it compils and runs.

Cheers.

**Comment by chernandezba** [comment]
Thanks . I will add it to the code

Cheers
