### ISSUE TITLE
Missing MacOS Binary Download

### ISSUE THREAD

**Issue by Xalior** [chernandezba/zesarux#5]
"Available versions for download here" seems "missing"

Can't find a link to a single available binary download on github, all download sources externally point to sourceforce which have been kindly updated with ever major release.... with a readme pointing to this github repo... where there are no binaries... :-/

-Dx

**Comment by chernandezba** [comment]
The releases section it’s on the home page. Like other github projects

**Comment by chernandezba** [comment]
“Here” means here, the web page. It’s not a broken link
About SF, forget it. ZEsarUX is not on sf anymore
