### ISSUE TITLE
GIF saving

### ISSUE THREAD

**Issue by Ygarr** [chernandezba/zesarux#7]
Save game view process into animated gif

**Comment by chernandezba** [comment]
Hi

Please read the following:

1) Please be more polite when writing. You are not talking with a machine, but a human (me), so expressions like "Hi", "Thanks", etc will be appreciated
2) This sections is for issues: tickets or doubts. If you have requests, send me an e-mail
3) The gif save functionality is already added on the TODO
4) Read the FAQ before writing here

Case closed

Thanks
Cesar

**Comment by Ygarr** [comment]
Ave, Caesar, morituri te salutant

**Comment by chernandezba** [comment]
Stop doing that or I will report it as spam. Thanks
