### ISSUE TITLE
Full screen on macOS

### ISSUE THREAD

**Issue by marca1969** [chernandezba/zesarux#8]
When passing from windowed to full screen mode the active area remains the same as that of the window, as imposed by the "setting/.../window size zoom" menu.

![schermata 2018-05-27 alle 12 33 05](https://user-images.githubusercontent.com/25556573/40584923-204bc43e-61aa-11e8-9d2c-f788fd53e824.png)

When a large enough window is selected (zoom 4 or 5), on the 16:9 screen of Macs (iMac for instance), the screen is used partially as expected, but the active part is left-bottom aligned and the remaining unused screen is red. 
It would be better to center the active part and black leave the remaining unused area.
Thanks for the attention & regards!

![schermata 2018-05-27 alle 12 20 43](https://user-images.githubusercontent.com/25556573/40584887-7ed9fe0e-61a9-11e8-92fa-45cfc302da4b.png)

**Comment by chernandezba** [comment]
Thanks for reporting. But it’s a know bug

**Comment by marca1969** [comment]
Thanks for your reply. Is this a bug of the macOS version or does it occur on the Linux version as well?

M.

**Comment by chernandezba** [comment]
No, it depends on the operating system and the video driver
