### ISSUE TITLE
Zesarux menu

### ISSUE THREAD

**Issue by marca1969** [chernandezba/zesarux#9]
Hello,
is it possible to remap the F5 key to another key combination? When using the recreated ZX Spectrum (RZXS) keyboard it would be useful  to open the menu without switching to another keyboard (with F keys). Passing from game mode to qwerty mode is not an option: when coming back to game mode the keyboard is not correctly recognised anymore.
In order to fix this, a key combination on the RZXS keyboard replacing the F5 and the ESC keys would be needed.
Thanks for the attention! Regards,

Massimiliano

**Comment by chernandezba** [comment]
Yes, just look on settings menu
